### ISSUE TITLE
Wrong implementation of base64 in MemoKin

### ISSUE THREAD

**Issue by DesKaOne** [kin-labs/kinetic-python-sdk#43]
#44 
Created : data: bytes = base64.b64decode(memo)
should be : data: bytes = base64.b64encode(memo)

If b64decode MemoKin in Transaction it doesn't appear, but if in b64encode MemoKin will appear in Transaction
-------------------------------------------------------------------------------------------------------------

import base64

from solana.publickey import PublicKey
from solana.transaction import TransactionInstruction

from kinetic_sdk.models import KinMemo, TransactionType

def create_memo_instruction(index: int, tx_type: TransactionType) -> TransactionInstruction:
    memo: bytearray = KinMemo.new(1, tx_type, index).val
    **data: bytes = base64.b64decode(memo)**

    return TransactionInstruction(
        data=data, keys=[], program_id=PublicKey("Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo")
    )

**Comment by beeman** [comment]
Thanks for the PR, this is released as `v1.0.0-rc.13-1`.

**Comment by DesKaOne** [comment]
#44
